#--------------------------------------------------------------------------
# ! The Docker Compose file is configured for local environments.
# ! Do not deploy the Caddy Docker Compose file in production environments.
#--------------------------------------------------------------------------

# Sets the project name.
name: docker-reverse-proxy

# The Docker services.
services:
  # The Caddy server container.
  caddy:
    # https://hub.docker.com/_/caddy
    image: caddy:alpine
    container_name: ${CONTAINER_NAME:-reverse_proxy}
    restart: unless-stopped
    networks:
      - reverse_proxy
    # Map the app container exposed port to the host port.
    ports:
      - 80:80
      - 443:443
      - ${ADMIN_API_PORT:-2019}:2019
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    # Caddy config
      - $PWD/config/Caddyfile:/etc/caddy/Caddyfile
    # Caddy certificate authority (CA)
      - $PWD/certificate-authority:/data/caddy/pki/authorities/local

# The Docker networks.
networks:
  reverse_proxy:
    driver: "bridge"
    name: ${NETWORK_NAME:-reverse_proxy}

# The Docker volumes.
volumes:
  caddy_data:
    driver: "local"
    name: "${CONTAINER_VOLUME_DATA_NAME:-reverse_proxy_data}"
  caddy_config:
    driver: "local"
    name: "${CONTAINER_VOLUME_CONFIG_NAME:-reverse_proxy_config}"
